Resolve compiler warning about _tree.
Add unused routines in order to suppress the error message:

include/RooTreeData.h:33:10: error: private field '_tree' is not used [-Werror,-Wunused-private-field]
  TTree *_tree ;           // TTree holding the data points
         ^

This re-apply commit f4d184e64190d7ad67075d052fb548d40e8a1de5 (May 10).